from graphviz import Digraph

dot = Digraph()
dot.attr('node', shape='box', style='rounded', fontname='Arial')
dot.attr('edge', fontname='Arial', fontsize='11')  # шрифт для подписей

dot.node('root', 'Число > 4?')
dot.node('l1', 'Число > 2?')
dot.node('r1', 'Число > 6?')
dot.node('ll', '>1?')
dot.node('lr', '>3?')
dot.node('rl', '>5?')
dot.node('rr', '>7?')
dot.node('lll', '1')
dot.node('llr', '2')
dot.node('lrl', '3')
dot.node('lrr', '4')
dot.node('rll', '5')
dot.node('rlr', '6')
dot.node('rrl', '7')
dot.node('rrr', '8')

# На всех вопросах: Да вправо, Нет влево (заменяем местами)
# labeldistance отодвигает подпись от стрелки
dot.edge('root', 'l1', label='Нет', labeldistance='3')
dot.edge('root', 'r1', label='Да', labeldistance='3')
dot.edge('l1', 'll', label='Нет', labeldistance='3')
dot.edge('l1', 'lr', label='Да', labeldistance='3')
dot.edge('r1', 'rl', label='Нет', labeldistance='3')
dot.edge('r1', 'rr', label='Да', labeldistance='3')
dot.edge('ll', 'lll', label='Нет', labeldistance='3')
dot.edge('ll', 'llr', label='Да', labeldistance='3')
dot.edge('lr', 'lrl', label='Нет', labeldistance='3')
dot.edge('lr', 'lrr', label='Да', labeldistance='3')
dot.edge('rl', 'rll', label='Нет', labeldistance='3')
dot.edge('rl', 'rlr', label='Да', labeldistance='3')
dot.edge('rr', 'rrl', label='Нет', labeldistance='3')
dot.edge('rr', 'rrr', label='Да', labeldistance='3')

dot.render('lessons/derevo_resheniy/assets/guess_number_tree', format='png', cleanup=True)
print('Done: guess_number_tree.png')